# Generated by Django 4.1.7 on 2023-04-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0003_detail_team_project_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='cv_file',
            field=models.ImageField(upload_to='cv/'),
        ),
    ]
