# Generated by Django 4.1.7 on 2023-05-16 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artyprod', '0005_alter_personnel_cv_file_alter_personnel_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='artyprod.personnel'),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(to='artyprod.project'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
